app/shop/models.py
from app.db import db


class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, index=True)

    products = db.relationship('Product',
                               backref='category')

    def __repr__(self):
        return f"<Category id: {self.id}, name: {self.name}>"


class Product(db.Model):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False, index=True)
    slug = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)
    image = db.Column(db.String(200))
    stocks = db.Column(db.Integer, default=0)
    price = db.Column(db.Float, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))


    carts = db.relationship('Cart', back_populates='product')
    ordered_products = db.relationship('OrderedProduct', back_populates='product')

    def __repr__(self):
        return f"<Product id: {self.id}, name: {self.name}>"

app/carts/views.py
from flask_login import current_user, login_required
from flask import Blueprint, flash, redirect, url_for, render_template, request

from app.db import db
from app.carts.models import Cart
from app.carts.forms import CartForm

blueprint = Blueprint('cart', __name__, url_prefix='/cart',
                      template_folder='templates/cart')


@blueprint.route("/", methods=['GET', 'POST'])
def cart():
    if current_user.is_anonymous:
        flash("Пожалуйста авторизуйтесь")
        return redirect(url_for('user.login'))

    form = CartForm()

    user_carts = get_user_carts(current_user.id)
    amount = user_carts['amount']
    total_product = user_carts['total_product']
    cart_items = user_carts['cart_items']

    return render_template('carts/cart.html', cart_items=cart_items,
                           amount=amount, form=form, total=total_product)


def get_user_carts(user):
    user_carts = Cart.query.filter_by(user_id=user).all()

    if not user_carts:
        return redirect(request.referrer or url_for('cart.cart'))

    amount = 0
    total_product = 0

    for item in user_carts:
        if item is None:
            continue
        else:
            total_product += int(item.quantity)
            amount += item.product.price * item.quantity

    return {"amount": amount, "total_product": total_product, "cart_items": user_carts}


def get_cart_item(product_id):
    try:
        cart_item = Cart.query.filter_by(user_id=current_user.id,
                                         product_id=product_id).first()
        return cart_item
    except:
        return flash('Товар не найден')


@blueprint.route("/add/<int:product_id>", methods=['POST'])
@login_required
def add_to_cart(product_id):
    cart_item = get_cart_item(product_id)

    if cart_item:
        cart_item.quantity += 1
    else:
        cart_item = Cart(user_id=current_user.id,
                         product_id=product_id,
                         quantity=1)
        db.session.add(cart_item)
        db.session.commit()
        flash(f"Товар {cart_item.product.name} добавлен в корзину")
        return redirect(request.referrer or url_for('shop.shop', product_id=product_id))

    db.session.commit()
    flash(f"Количество {cart_item.product.name} увеличено")
    return redirect(request.referrer or url_for('shop.shop', product_id=product_id))


@blueprint.route("/remove/<int:product_id>", methods=['POST'])
@login_required
def remove_from_cart(product_id):
    cart_item = get_cart_item(product_id)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        flash(f"Количество {cart_item.product.name} уменьшено")
    else:
        product_name = cart_item.product.name
        db.session.delete(cart_item)
        flash(f"Товар {product_name} удалён из корзины")

    db.session.commit()
    return redirect(request.referrer or url_for('shop.shop'))


@blueprint.route("/delete/<int:product_id>", methods=['POST'])
@login_required
def delete_product(product_id):
    cart_item = get_cart_item(product_id)

    if cart_item:
        product_name = cart_item.product.name
        db.session.delete(cart_item)
        db.session.commit()
        flash(f"Товар {product_name} удалён из корзины")

    else:
        flash("Такого товара нет в вашей корзине")
    return redirect(request.referrer or url_for('shop.shop'))


@blueprint.route("/delete/<int:cart>", methods=['POST'])
@login_required
def delete_cart():
    cart_item = Cart.query.filter(Cart.id == cart.id).filter(Cart.user_id == current_user.id).first()
    if cart is None:
        db.session.delete(cart)
        db.session.commit()
    else:
        db.session.delete(cart_item)
        db.session.commit()

    return redirect(request.referrer or url_for('shop.shop'))

app/shop/views.py
from flask import render_template, Blueprint

from app.shop.models import Product

blueprint = Blueprint('shop', __name__, url_prefix='/shop', template_folder='templates/shop')




@blueprint.route("/")
def shop():
    page_title = 'Магазин'
    products_list = Product.query.order_by(Product.id).all()
    return render_template('shop/shop.html',
                           page_title=page_title, products=products_list, content="Товары")



@blueprint.route('/<int:product_id>')
def product(product_id):
    product = Product.query.get_or_404(product_id)
    title = f"Страница продукта {product.slug}"
    content = 'Страничка продукта'
    return render_template('shop/product.html',
                           page_title=title, content=content, product=product)



@blueprint.route('/cat/<int:category_id>')
def select_category(category_id):
    if category_id == 0:
        products_list = Product.query.order_by(Product.id).all()
        return render_template('shop/shop.html',
                               products=products_list, content="Товары")

    else:
        products_list = Product.query.filter_by(category_id=category_id).order_by(Product.id).all()

    return render_template('shop/shop.html',
                           page_title=f'Товары категории да', products=products_list)

app/templates/shop/product.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}


{% block content %}

{% if product %}
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                <img src="{{ url_for('static', filename='media/products/' + product.image) }}" class="img-thumbnail"
                     data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-3">Осталось на складе: {{ product.stocks }}</p>
            </div>
            <!-- Увеличить изображение в модальном окне -->
            <div class="modal fade" id="imageModal1" tabindex="-1" aria-labelledby="imageModal1Label"
                 aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">{{ product.image }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            <img src="../deps/images/goods/set of tea table and three chairs.jpg" class="img-fluid"
                                 alt="Изображение 1">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Описание товара -->
        <div class="card-body">
            <p class="card-text">Цена: <strong>{{ product.price }}</strong></p>
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description}}</p>
            <a href="" class="btn btn-dark add-to-cart">Добавить в корзину</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/shop/shop.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}


{% block content %}

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-12 col-md-8 mx-auto">
            <h1 class="fw-light">Магазин</h1>
            <p class="lead text-body-secondary">Самое лучшее описание самого лучшего магазина</p>
            <p>
                <a href="{{ url_for('shop.select_category', category_id=0) }}" class="btn btn-primary my-2">Все товары</a>
                <a href="{{ url_for('shop.select_category', category_id=2) }}" class="btn btn-primary my-2">Для женщин</a>
                <a href="{{ url_for('shop.select_category', category_id=1) }}" class="btn btn-primary my-2">Для мужчин</a>
                <a href="{{ url_for('shop.select_category', category_id=3) }}" class="btn btn-primary my-2">Для детей</a>
            </p>
        </div>
    </div>
</section>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for product in products %}
        <div class="col">
            <div class="card border-primary rounded custom-shadow">
                <img src="{{ url_for('static', filename='media/products/' + product.image) }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{{ url_for('shop.product', product_id=product.id)}}">
                        <p class="card-title">{{ product.name }}</p>
                    </a>
                    <p class="card-text text-truncate">{{ product.description }}</p>
                    <p class="product_id">Осталось на складе: {{ product.stocks }}</p>
                    <div class="d-flex justify-content-between">
<!--                        <p><s>100</s> P</p>-->
                        <p><strong>{{ product.price }}</strong></p>
<!--                        <span class="badge bg-warning text-dark">Скидка 10.00 %</span>-->
<!--                         <p><strong>100.00 $</strong></p>-->
                        <form action="{{ url_for('cart.add_to_cart', product_id=product.id) }}" method="POST">
                            <button type="submit" class="btn btn-link p-0 m-0">
                            <img class="mx-1" src="{{ url_for('static', filename='img/cart.png') }}" alt="Catalog Icon" width="32" height="32">
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{{ content }}
{% endblock %}