app/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app.db import db

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False)
    username = db.Column(db.String(), nullable=False)
    password = db.Column(db.String())
    role = db.Column(db.String(20), nullable=False, default='user')

    cart = db.relationship("Cart", back_populates="user")
    orders = db.relationship("Order", back_populates="user")

    @property
    def is_admin(self):
        return self.role == 'admin'

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return f"<User {self.email}>"

app/user/forms.py
from flask import Blueprint
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length

from app.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/user')


class LoginForm(FlaskForm):
    username = StringField("Имя пользователя",
                           validators=[DataRequired()],
                           render_kw={"class": "form-control"})

    password = PasswordField('Пароль',
                             validators=[DataRequired()],
                             render_kw={"class": "form-control"})

    submit = SubmitField("Отправить",
                         render_kw={"class": "btn btn-primary w-100 py-2"})

    remember_me = BooleanField("Запомнить меня",
                               default=True,
                               render_kw={"class": "form-check-input"})


class RegistrationForm(FlaskForm):
    username = StringField('Введите имя',
                           validators=[DataRequired()],
                           render_kw={"class": "form-control"})

    email = StringField('Введите Email',
                        validators=[DataRequired(),
                                    Email('Введен некоректный Email')],
                        render_kw={"class": "form-control"})

    password = PasswordField('Введите пароль',
                             validators=[DataRequired(),
                                         Length(min=6)],
                             render_kw={"class": "form-control",
                                        "placeholder": "Не менее 6 символов"})
    password2 = PasswordField('Повторите пароль',
                              validators=[DataRequired(),
                                          EqualTo('password',
                                                  'Введенные пароли не совпадают')],
                              render_kw={"class": "form-control", "placeholder": "Повторите пароль"})

    submit = SubmitField('Зарегистрироваться',
                         render_kw={"class": "btn btn-primary w-100"})

    def validate_username(self, username):
        user_count = User.query.filter(User.username.ilike(username.data)).first()
        if user_count:
            raise ValidationError('Пользователь с таким именем уже существует')

    def validate_email(self, email):
        user_count = User.query.filter(User.email.ilike(email.data)).first()
        if user_count:
            raise ValidationError('Пользователь с таким Email уже существует')

app/shop/views.py
from flask import render_template, Blueprint

from app.shop.models import Product

blueprint = Blueprint('shop', __name__, url_prefix='/shop', template_folder='templates/shop')




@blueprint.route("/")
def shop():
    page_title = 'Магазин'
    products_list = Product.query.order_by(Product.id).all()
    return render_template('shop/shop.html',
                           page_title=page_title, products=products_list, content="Товары")



@blueprint.route('/<int:product_id>')
def product(product_id):
    product = Product.query.get_or_404(product_id)
    title = f"Страница продукта {product.slug}"
    content = 'Страничка продукта'
    return render_template('shop/product.html',
                           page_title=title, content=content, product=product)



@blueprint.route('/cat/<int:category_id>')
def select_category(category_id):
    if category_id == 0:
        products_list = Product.query.order_by(Product.id).all()
        return render_template('shop/shop.html',
                               products=products_list, content="Товары")

    else:
        products_list = Product.query.filter_by(category_id=category_id).order_by(Product.id).all()

    return render_template('shop/shop.html',
                           page_title=f'Товары категории да', products=products_list)

app/user/views.py
from flask import Blueprint, flash, redirect, url_for, render_template
from flask_login import login_user, logout_user, current_user
from app.user.forms import LoginForm, RegistrationForm
from app.user.models import User, db
from sqlalchemy.exc import SQLAlchemyError


from app.carts.forms import CartForm
from app.orders.models import Order
from app.carts.views import get_user_carts

blueprint = Blueprint('user', __name__,
                      url_prefix='/user',
                      template_folder='templates/user')


@blueprint.route("/register", methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        flash('Вы уже авторизованы')
        return redirect(url_for('main.index'))
    form = RegistrationForm()

    if form.validate_on_submit():
        try:
            new_user = User(username=form.username.data, email=form.email.data)
            new_user.set_password(form.password.data)

            db.session.add(new_user)

            db.session.commit()
            flash("Вы успешно зарегистрировались")
            return redirect(url_for("user.login"))

        except SQLAlchemyError:
            db.session.rollback()
            flash("Произошла ошибка при записи в базу данных")
            return redirect(url_for('user.register'))

    return render_template('user/register.html',
                           page_title='Регистрация', form=form)


@blueprint.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()

    return render_template('user/login.html',
                           page_title="Авторизация", form=form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт")
            return redirect(url_for("main.index"))

    flash("Неправильный логин или пароль")
    return redirect(url_for("user.login"))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно вышли')
    return redirect(url_for('main.index'))


@blueprint.route('/profile')
def profile():
    if current_user.is_anonymous:
        flash('Для доступа в личный кабинет авторизуйтесь')
        return redirect(url_for("user.login"))
    #Отображение корзины
    cart_form = CartForm()
    user = current_user.id

    user_carts = get_user_carts(user)
    amount = user_carts['amount']
    total_product = user_carts['total_product']
    cart_items = user_carts['cart_items']

    #Отображение заказа
    orders = Order.query.filter_by(user_id=user).all()

    print(orders)

    return render_template('user/profile.html',
                           content='Заказ',
                           cart_items=cart_items,
                           form=cart_form,
                           orders=orders,
                           total=total_product,
                           amount=amount)

app/templates/user/login.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}


{% block content %}
<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
            <form action="{{ url_for('user.process_login') }}" method="POST" class="border p-4 rounded shadow-sm">
                {{ form.hidden_tag() }}
                <img class="mb-3 mx-auto d-block" src="{{ url_for('static', filename='img/logo.png') }}" alt=""
                     width="72" height="57">
                <div class="form-group mb-4">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group mb-4">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                <div class="form-group form-check mb-4">
                    {{ form.remember_me() }}
                    {{ form.remember_me.label(class_='form-check-label') }}
                </div>
                <div class="form-group mb-4">
                    {{ form.submit() }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="col-lg-10">
    <!-- Контент на странице -->
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->

                <!-- Корзина -->
                <h3 class="text-center">Корзина</h3>
                {% include 'carts/cart_for_include.html'%}
                <!-- Закончилась разметка корзины -->
            </div>
            <a class="btn btn-primary" href="../orders/create_order.html">
                Оформить заказ
            </a>
        </div>
    </div>
    <!-- Оформленные заказы -->

    <div class="col-md-12">
        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
            <h3 class="text-center mb-4">Мои заказы</h3>

            <!-- Разметка заказов -->
            {% if orders %}
                {% for order in orders %}
            <div class="container">
                <div class="accordion" id="accordionExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="heading1">
                            <button class="accordion-button collapsed" type="button"
                                    data-bs-toggle="collapse" data-bs-target="#collapse1"
                                    aria-expanded="false" aria-controls="collapse1">
                                Заказ № {{ order.id }} - {{ order.create_time }} | Статус:<strong class="mx-2"> {{ order.status }}</strong>
                            </button>
                        </h2>
                        <div id="collapse1" class="accordion-collapse collapse" aria-labelledby="heading1"
                             data-bs-parent="#accordionExample" style="">
                            <div class="accordion-body">
                                <table class="table table-dark table-hover">
                                    <thead>
                                    <tr>
                                        <th>Товар</th>
                                        <th>Количество</th>
                                        <th>Цена</th>
                                        <th>Общая стоимость</th>
                                    </tr>
                                    </thead>
                                    {% for product in  order.ordered_products %}
                                    <tbody>
                                    <tr>
                                        <td><a class="text-white" href="{{ url_for('shop.product', product_id=product.product_id)}}">{{ product.name }}</a>
                                        </td>
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.quantity * product.price }}</td>

                                    </tr>
                                    </tbody>
                                    {% endfor %}
                                </table>
                                <div class="d-flex justify-content-between">
                                    <p><strong>Итого:</strong></p>
                                    <p><strong>{{ order.total_amount }}</strong></p>

                                </div>

                            </div>

                        </div>
                    </div>

            {% endfor %}
            {% endif %}
            <!-- Закончилась разметка заказов -->
        </div>
    </div>
</div>

{% endblock %}

app/templates/user/register.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
            <form action="{{ url_for('user.register') }}" method="POST" class="border p-4 rounded shadow-sm">
                <img class="mb-3 mx-auto d-block" src="{{ url_for('static', filename='img/logo.png') }}" alt=""
                     width="72" height="57">
                    {{ form.hidden_tag() }}
                <div class="form-group mb-4">
                    {{ form.username.label }}
                    {{ form.username() }}

                    {% for error in form.username.errors %}
                        <span style="color: red;">{{ error }}</span>
                    {% endfor %}

                </div>
                <div class="form-group mb-4">
                    {{ form.email.label }}
                    {{ form.email() }}

                    {% for error in form.email.errors %}
                        <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group mb-4">
                    {{ form.password.label }}
                    {{ form.password() }}

                    {% for error in form.password.errors %}
                        <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group mb-4">
                    {{ form.password2.label }}
                    {{ form.password2() }}

                    {% for error in form.password2.errors %}
                        <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-group mb-4">
                    {{ form.submit() }}
                </div>
                <div class="form-group mb-4">
                    <span class="text-body-secondary">Уже есть аккаунт?</span>
                    <a class="btn btn-outline-primary float-end" href="{{ url_for('user.login') }}"
                       role="button">Войти</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}