app/carts/models.py
from app.db import db


class Cart(db.Model):
    __tablename__ = 'carts'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False, index=True)
    product_id = db.Column(db.Integer, db.ForeignKey('products.id'), nullable=False)
    quantity = db.Column(db.Integer, default=1)

    user = db.relationship("User", back_populates="cart")
    product = db.relationship("Product", back_populates="carts")

    def __repr__(self):
        return f"<Cart(user_id={self.user_id}, product_id={self.product_id}, quantity={self.quantity})>"

app/carts/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField


class CartForm(FlaskForm):

    submit_increase = SubmitField("+", render_kw={"class": "btn btn-primary btn-sm"})

    submit_decrease = SubmitField("-", render_kw= {"class": "btn btn-primary btn-sm"})

    submit_order = SubmitField("Оформить заказ", render_kw={"class": "btn btn-primary"})

app/carts/views.py
from flask_login import current_user, login_required
from flask import Blueprint, flash, redirect, url_for, render_template, request

from app.db import db
from app.carts.models import Cart
from app.carts.forms import CartForm

blueprint = Blueprint('cart', __name__, url_prefix='/cart',
                      template_folder='templates/cart')


@blueprint.route("/", methods=['GET', 'POST'])
def cart():
    if current_user.is_anonymous:
        flash("Пожалуйста авторизуйтесь")
        return redirect(url_for('user.login'))

    form = CartForm()

    user_carts = get_user_carts(current_user.id)
    amount = user_carts['amount']
    total_product = user_carts['total_product']
    cart_items = user_carts['cart_items']

    return render_template('carts/cart.html', cart_items=cart_items,
                           amount=amount, form=form, total=total_product)


def get_user_carts(user):
    user_carts = Cart.query.filter_by(user_id=user).all()

    if not user_carts:
        return redirect(request.referrer or url_for('cart.cart'))

    amount = 0
    total_product = 0

    for item in user_carts:
        if item is None:
            continue
        else:
            total_product += int(item.quantity)
            amount += item.product.price * item.quantity

    return {"amount": amount, "total_product": total_product, "cart_items": user_carts}


def get_cart_item(product_id):
    try:
        cart_item = Cart.query.filter_by(user_id=current_user.id,
                                         product_id=product_id).first()
        return cart_item
    except:
        return flash('Товар не найден')


@blueprint.route("/add/<int:product_id>", methods=['POST'])
@login_required
def add_to_cart(product_id):
    cart_item = get_cart_item(product_id)

    if cart_item:
        cart_item.quantity += 1
    else:
        cart_item = Cart(user_id=current_user.id,
                         product_id=product_id,
                         quantity=1)
        db.session.add(cart_item)
        db.session.commit()
        flash(f"Товар {cart_item.product.name} добавлен в корзину")
        return redirect(request.referrer or url_for('shop.shop', product_id=product_id))

    db.session.commit()
    flash(f"Количество {cart_item.product.name} увеличено")
    return redirect(request.referrer or url_for('shop.shop', product_id=product_id))


@blueprint.route("/remove/<int:product_id>", methods=['POST'])
@login_required
def remove_from_cart(product_id):
    cart_item = get_cart_item(product_id)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        flash(f"Количество {cart_item.product.name} уменьшено")
    else:
        product_name = cart_item.product.name
        db.session.delete(cart_item)
        flash(f"Товар {product_name} удалён из корзины")

    db.session.commit()
    return redirect(request.referrer or url_for('shop.shop'))


@blueprint.route("/delete/<int:product_id>", methods=['POST'])
@login_required
def delete_product(product_id):
    cart_item = get_cart_item(product_id)

    if cart_item:
        product_name = cart_item.product.name
        db.session.delete(cart_item)
        db.session.commit()
        flash(f"Товар {product_name} удалён из корзины")

    else:
        flash("Такого товара нет в вашей корзине")
    return redirect(request.referrer or url_for('shop.shop'))


@blueprint.route("/delete/<int:cart>", methods=['POST'])
@login_required
def delete_cart():
    cart_item = Cart.query.filter(Cart.id == cart.id).filter(Cart.user_id == current_user.id).first()
    if cart is None:
        db.session.delete(cart)
        db.session.commit()
    else:
        db.session.delete(cart_item)
        db.session.commit()

    return redirect(request.referrer or url_for('shop.shop'))

app/orders/views.py
from flask import render_template, Blueprint, redirect, url_for, flash, request
from flask_login import current_user, login_required
from sqlalchemy.exc import SQLAlchemyError

from app.db import db
from app.carts.models import Cart
from app.orders.models import Order, OrderedProduct
from app.carts.forms import CartForm
from app.carts.views import get_user_carts
from app.orders.forms import OrderForm

blueprint = Blueprint('order', __name__, url_prefix='/order')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def preview_orders():
    user = current_user.id
    cart_form = CartForm()
    order_form = OrderForm()

    user_carts = get_user_carts(user)
    amount = user_carts['amount']
    total_product = user_carts['total_product']
    cart_items = user_carts['cart_items']

    return render_template('orders/order.html',
                           content='Заказ',
                           cart_items=cart_items,
                           form=cart_form,
                           order_form=order_form,
                           total=total_product,
                           amount=amount)



@blueprint.route('/process-order', methods=['GET', 'POST'])
@login_required
def create_order():
    order_form = OrderForm()
    cart_form = CartForm()
    user = current_user.id
    cart_items = get_user_carts(user)["cart_items"]

    if not cart_items:
        flash("Ваша корзина пуста")
        return redirect(url_for('cart.cart'))

    if order_form.validate_on_submit():

        for cart_item in cart_items:
            if cart_item.product.stocks < cart_item.quantity:
                flash(
                    f"Недостаточное количество товара {cart_item.product.name} на складе, в наличии {cart_item.product.quantity}")
                return redirect(url_for('cart.cart'))

        try:
            order = Order(
                user_id=user,
                first_name=order_form.first_name.data,
                last_name=order_form.last_name.data,
                phone_number=order_form.phone_number.data,
                delivery_method=order_form.delivery_method.data,
                address=order_form.address.data,
                payment=order_form.pay_method.data,
            )
            db.session.add(order)

            for cart_item in cart_items:
                product = cart_item.product
                ordered_product = OrderedProduct(
                    name=product.name,
                    product_id=cart_item.product.id,
                    quantity=cart_item.quantity,
                    price=product.price,
                    order=order
                )
                db.session.add(ordered_product)
                product.stocks -= cart_item.quantity

                db.session.delete(cart_item)

            db.session.commit()
            flash("Заказ успешно оформлен!")
            return redirect(url_for("main.index"))

        except SQLAlchemyError as e:
            db.session.rollback()
            flash(f"Произошла ошибка при оформлении заказа: {str(e)}")
            return redirect(url_for('cart.cart'))

    else:
        return render_template("orders/order.html",
                               order_form=order_form,
                               cart_items=cart_items,
                               form=cart_form)

app/templates/carts/cart.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}


{% block content %}
        {% if cart_items %}
            {% include 'carts/cart_for_include.html'%}


            <div class="card mb-3 shadow-lg">
                <div class="card-footer">
                    <p class="float-left">Итого {{ total }} товар(а) на сумму</p>
                    <h4 class="float-left"><strong>{{ amount }} P</strong></h4>
                </div>
            </div>
            <!-- Закончилась разметка корзины -->
        <a href="{{ url_for('order.preview_orders') }}" type="submit" class="btn btn-primary">
            Оформить заказ
        </a>
    </div>
</div>
{% else %}
<div class="alert alert-info text-center">
    Ваша корзина пуста
</div>
<div class="text-center">
    <a href="{{ url_for('shop.shop') }}" class="btn btn-primary">
        Вернуться к покупкам
    </a>
</div>
{% endif %}

{% endblock %}

app/templates/carts/cart_for_include.html
<div class="card mb-3 text-bg-light shadow-lg">
    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
        <div class="container" id="cart-items-container">

            {% for item in cart_items %}
            {% if item %}
            <div class="card mb-3 text-bg-light shadow-lg">
                <div class="card-header">
                    <h5 class="card-title">{{ item.product.name }}</h5>
                </div>

                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row text-center">
                            <div class="col p-0">
                                <div class="input-group">

                                    <form action="{{ url_for('cart.remove_from_cart', product_id=item.product.id) }}"
                                          method="POST" class="input-group-btn">
                                        {{ form.submit_decrease }}
                                    </form>

                                    <input type="row text-center" class="form-control number" value={{ item.quantity }}
                                           readonly>

                                    <form action="{{  url_for('cart.add_to_cart', product_id=item.product.id)  }}"
                                          method="POST" class="input-group-btn">
                                        {{ form.submit_increase }}
                                    </form>

                                </div>
                            </div>
                            <div class="col p-0">
                                <p>x {{ item.product.price }} = </p>
                            </div>
                            <div class="col p-0">{{ item.product.price * item.quantity }}</div>
                            <div class="col p-0">
                                <form action="{{ url_for('cart.delete_product', product_id=item.product.id) }}"
                                      method="POST">
                                    <button type="submit" class="btn btn-link p-0 m-0">
                                        <img class="mx-1" src="{{ url_for('static', filename='img/del_cart.png') }}"
                                             alt="Catalog Icon" width="20" height="20">
                                    </button>
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
                {% else %}
                <div class="alert alert-warning">
                    Товар был удален
                    <form action="{{ url_for('cart.delete_cart', cart=item) }}" method="POST">
                        <button type="submit" class="btn btn-sm btn-outline-danger">Очистить</button>
                    </form>
                </div>
                {% endif %}
            </div>
            {% endfor %}
            <div class="card mb-3 shadow-lg">
                <div class="card-footer">
                    <p class="float-left">Итого {{ total }} товар(а) на сумму</p>
                    <h4 class="float-left"><strong>{{ amount }} P</strong></h4>
                </div>
            </div>
            <!-- Закончилась разметка корзины -->

        </div>
    </div>
</div>