app/shop/models.py
from app.db import db


class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, index=True)

    products = db.relationship('Product',
                               backref='category')

    def __repr__(self):
        return f"<Category id: {self.id}, name: {self.name}>"


class Product(db.Model):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False, index=True)
    slug = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)
    image = db.Column(db.String(200))
    stocks = db.Column(db.Integer, default=0)
    price = db.Column(db.Float, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))


    carts = db.relationship('Cart', back_populates='product')
    ordered_products = db.relationship('OrderedProduct', back_populates='product')

    def __repr__(self):
        return f"<Product id: {self.id}, name: {self.name}>"

app/main/views.py
from flask import render_template, Blueprint

blueprint = Blueprint('main', __name__)


@blueprint.route("/", methods=['POST', 'GET'])
def index():
    page_title = 'Главная страница'
    content = 'Главная страница'
    return render_template('main/index.html',
                           page_title=page_title, content=content)


@blueprint.route("/about")
def about():
    page_title = 'О нас'
    content = 'Страница о нас'
    return render_template('main/about.html',
                           page_title=page_title, content=content)


@blueprint.route("/contacts")
def contacts():
    page_title = 'Контакты'
    content = 'Страница с контактами'
    return render_template('main/contacts.html',
                           page_title=page_title, content=content)


@blueprint.route("/questions")
def questions():
    page_title = 'Вопросы'
    content = 'Страница с вопросами'
    return render_template('main/questions.html',
                           page_title=page_title, content=content)

app/shop/views.py
from flask import render_template, Blueprint

from app.shop.models import Product

blueprint = Blueprint('shop', __name__, url_prefix='/shop', template_folder='templates/shop')




@blueprint.route("/")
def shop():
    page_title = 'Магазин'
    products_list = Product.query.order_by(Product.id).all()
    return render_template('shop/shop.html',
                           page_title=page_title, products=products_list, content="Товары")



@blueprint.route('/<int:product_id>')
def product(product_id):
    product = Product.query.get_or_404(product_id)
    title = f"Страница продукта {product.slug}"
    content = 'Страничка продукта'
    return render_template('shop/product.html',
                           page_title=title, content=content, product=product)



@blueprint.route('/cat/<int:category_id>')
def select_category(category_id):
    if category_id == 0:
        products_list = Product.query.order_by(Product.id).all()
        return render_template('shop/shop.html',
                               products=products_list, content="Товары")

    else:
        products_list = Product.query.filter_by(category_id=category_id).order_by(Product.id).all()

    return render_template('shop/shop.html',
                           page_title=f'Товары категории да', products=products_list)

app/user/views.py
from flask import Blueprint, flash, redirect, url_for, render_template
from flask_login import login_user, logout_user, current_user
from app.user.forms import LoginForm, RegistrationForm
from app.user.models import User, db
from sqlalchemy.exc import SQLAlchemyError


from app.carts.forms import CartForm
from app.orders.models import Order
from app.carts.views import get_user_carts

blueprint = Blueprint('user', __name__,
                      url_prefix='/user',
                      template_folder='templates/user')


@blueprint.route("/register", methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        flash('Вы уже авторизованы')
        return redirect(url_for('main.index'))
    form = RegistrationForm()

    if form.validate_on_submit():
        try:
            new_user = User(username=form.username.data, email=form.email.data)
            new_user.set_password(form.password.data)

            db.session.add(new_user)

            db.session.commit()
            flash("Вы успешно зарегистрировались")
            return redirect(url_for("user.login"))

        except SQLAlchemyError:
            db.session.rollback()
            flash("Произошла ошибка при записи в базу данных")
            return redirect(url_for('user.register'))

    return render_template('user/register.html',
                           page_title='Регистрация', form=form)


@blueprint.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()

    return render_template('user/login.html',
                           page_title="Авторизация", form=form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт")
            return redirect(url_for("main.index"))

    flash("Неправильный логин или пароль")
    return redirect(url_for("user.login"))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно вышли')
    return redirect(url_for('main.index'))


@blueprint.route('/profile')
def profile():
    if current_user.is_anonymous:
        flash('Для доступа в личный кабинет авторизуйтесь')
        return redirect(url_for("user.login"))
    #Отображение корзины
    cart_form = CartForm()
    user = current_user.id

    user_carts = get_user_carts(user)
    amount = user_carts['amount']
    total_product = user_carts['total_product']
    cart_items = user_carts['cart_items']

    #Отображение заказа
    orders = Order.query.filter_by(user_id=user).all()

    print(orders)

    return render_template('user/profile.html',
                           content='Заказ',
                           cart_items=cart_items,
                           form=cart_form,
                           orders=orders,
                           total=total_product,
                           amount=amount)

app/templates/about.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}


{% block content %}
{{ content }}
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>

<body class="d-flex flex-column min-vh-100">
    {% include 'header.html'%}


<main class="container mt-5 " style="padding-top: 80px;">
  <div class="row justify-content-center align-items-center">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="alert alert-warning" role="alert">
        {% for message in messages %}
          {{ message }}<br>
        {% endfor %}
      </div>
        {% endif %}
        {% endwith %}

    {% block content %}{% endblock %}
  </div>
</main>

 {% include 'footer.html'%}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

app/templates/footer.html
<footer class="bg-white border-top mt-auto">
  <div class="container">
    <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
            <img class="header__img" height="30" width="30" src="{{ url_for('static', filename='img/logo.png') }}" alt="logo">
          </a>
        <span class="mb-3 mb-md-0 text-body-secondary">    2024 Company, Inc</span>
      </div>

      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-body-secondary" href="https://vk.com/il1uminaterrr"><img class="header__img" height="30" width="30" src="{{ url_for('static', filename='img/vk.png') }}" alt="VK"></a></li>
        <li class="ms-3"><a class="text-body-secondary" href="https://t.me/Il1uminater"><img class="header__img" height="30" width="30" src="{{ url_for('static', filename='img/telegram.png') }}" alt="TG"></a></li>
        <li class="ms-3"><a class="text-body-secondary" href="/"><img class="header__img" height="30" width="30" src="{{ url_for('static', filename='img/inst.png') }}" alt="low"></a></li>
      </ul>
    </div>
  </div>
</footer>

app/templates/header.html
<header class="fixed-top bg-white shadow-sm">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-3 border-bottom">
            <div class="col-md-3 mb-2 mb-md-0">
                <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
                    <img class="header__img" height="48" width="48"
                         src="{{ url_for('static', filename='img/logo.png') }}" alt="logo">
                </a>
            </div>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{ url_for('main.index') }}" class="nav-link px-2 link-secondary">Главная</a></li>
                <li><a href="{{ url_for('shop.shop') }}" class="nav-link px-2">Магазин</a></li>
                <li><a href="{{ url_for('main.contacts') }}" class="nav-link px-2">Контакты</a></li>
                <li><a href="{{ url_for('main.questions') }}" class="nav-link px-2">FAQs</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('user.profile') }}" class="nav-link px-2">Личный кабинет</a></li>
                {% endif %}
            </ul>
            <div class="col-md-3 text-end">
                {% if current_user.is_authenticated %}
                    {% if current_user.is_admin  %}
                        <a class="btn btn-primary" href="{{ url_for('admin.index') }}">Админка</a>
                    {% endif %}
                    <a class="btn btn-outline-primary" href="{{ url_for('user.logout') }}" role="button">Выйти</a>
                    <a class="btn btn-outline-primary" href="{{ url_for('cart.cart') }}" role="button">Корзина</a>
                {% else %}
                    <a class="btn btn-outline-primary" href="{{ url_for('user.login') }}" role="button">Войти</a>
                    <a class="btn btn-primary" href="{{ url_for('user.register') }}">Зарегистрироваться</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}


{% block content %}   
{{ content }}        
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}

{% block content %}

<div class="row justify-content-center mt-5">
  <div class="col-md-6 col-lg-12">
  <form action="{{ url_for('process_login') }}" method="POST" class="border p-4 rounded shadow-sm">
    <img class="mb-3 mx-auto d-block" src="{{ url_for('static', filename='img/logo.png') }}" alt="" width="72" height="57">
      {{ form.hidden_tag() }}
      <div class="form-group mb-3">
        {{ form.username.label }}
        {{ form.username() }}
      </div>
      <div class="form-group mb-3">
        {{ form.password.label }}
        {{ form.password() }}
      </div>
    <div class="form-group form-check">
      {{ form.remember_me() }}
      {{ form.remember_me.label(class_='form-check-label') }}
    </div>
    <div class="form-group mb-4">
      {{ form.submit() }}
    </div>
  </form>
      </div>
</div>
{% endblock %}

app/templates/page_error.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> 404 page not found</title>
  <link rel="shortcut icon" type="image/png" href="#">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
<style>
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&family=Roboto&family=Playfair+Display&display=swap");

html {
    scroll-behavior: smooth;
}

body {
    font-family: "Roboto", sans-serif;
    color: #6f6f6f;
    font-size: 16px;
    padding: 0;
    margin: 0;
    font-weight: 400;
    position: relative;
    line-height: 1.7;
    background-color: #f8f6ff;
}

img {
    max-width: 100%;
    height: auto;
}

h1 {
    font-size: 62px;
}

h2 {
    font-size: 32px;
}

@media (max-width: 991px) {
    h2 {
        font-size: 36px;
    }
}

@media (max-width: 575px) {
    h2 {
        font-size: 28px;
    }
}

h3 {
    font-size: 24px;
}

h4 {
    font-size: 22px;
}

@media (max-width: 767px) {
    h4 {
        font-size: 20px;
    }
}

h5 {
    font-size: 20px;
}

@media (max-width: 767px) {
    h5 {
        font-size: 18px;
    }
}

h6 {
    font-size: 18px;
}

h1,
h2,
h3,
h4,
h5,
h6 {
    font-family: "Poppins", sans-serif;
    color: #525252;
    font-weight: 600;
    margin: 0;
    line-height: 1.4;
}

h1>a,
h2>a,
h3>a,
h4>a,
h5>a,
h6>a {
    font-family: "Poppins", sans-serif;
    color: #525252;
    font-weight: 600;
    -webkit-transition: all 0.3s;
    -o-transition: all 0.3s;
    transition: all 0.3s;
    line-height: 1.4;
}

p,
li,
span {
    margin: 0;
}

a {
    text-decoration: none;
    display: inline-block;
    font-family: "Roboto", sans-serif;
    font-weight: 400;
}

a:hover {
    text-decoration: none;
}

.cmn-btn {
    padding: 12px 35px;
    text-transform: uppercase;
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    -ms-border-radius: 5px;
    -o-border-radius: 5px;
    background-color: #6e41ff;
    box-shadow: 0px 10px 20px 0px rgba(0, 0, 0, 0.15);
    -webkit-transition: all 0.3s;
    -o-transition: all 0.3s;
    transition: all 0.3s;
    color: #ffffff;
}

.cmn-btn:hover {
    color: #ffffff;
    background-color: #5b28ff;
}

.error {
    position: relative;
    padding: 120px 0;
}

.error .title {
    font-size: 42px;
    margin-top: 30px;
    margin-bottom: 15px;
}

@media (max-width: 480px) {
    .error .title {
        font-size: 32px;
    }
}

.error .title b {
    font-size: 72px;
    color: #f45570;
}

.error p {
    font-size: 18px;
}
</style>
</head>
  <body>


  <div class="error">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-7 text-center">
          <img src="{{ url_for('static', filename='img/error-404.png') }}" alt="Страница не найдена (ошибка 404)">
          <h2><b>404</b> Страница не найдена</h2>
          <p>посетите главную страницу <br> возможно вы найдёте её</p>
          <a href="{{ url_for('main.index') }}" class="cmn-btn mt-4">На главную</a>
        </div>
      </div>
    </div>
  </div>


  </body>
</html>

app/templates/shop.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}


{% block content %}
{{ content }}
{% endblock %}